basePath: /api/v1
definitions:
  serializers.RegisterResponse:
    properties:
      ID:
        type: integer
      token:
        type: string
    type: object
  validators.RegisterValidator:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
host: localhost:80
info:
  contact:
    email: wenzzy.belkov@gmail.com
    name: Wenzzy Belkov
    url: https://github.com/WenzzyX
  description: This is a sample server for create short urls.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Go-Ushorter API
  version: "1.0"
paths:
  /auth/registration:
    get:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/validators.RegisterValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializers.RegisterResponse'
      summary: User registration
      tags:
      - Auth
swagger: "2.0"
