
# Registration withour password field
POST {{baseUrl}}/auth/registration
Accept: application/json
Content-Type: application/json


{
  "email": "test.mail@testmail.qwerty"
}

###

# Registration withour password field
POST {{baseUrl}}/auth/registration
Accept: application/json
Content-Type: application/json


{
  "email": "test.mail@testmail.qwerty",
  "password": "testQuerty1243@@"
}
