# Get all links (without auth)
GET {{baseUrl}}/links
Accept: application/json

###


# Get all links (with auth)
GET {{baseUrl}}/links?page=2&take=10
Accept: application/json
Authorization: Bearer {{accessToken}}

###


# Create new link
POST {{baseUrl}}/links
Accept: application/json
Authorization: Bearer {{accessToken}}
Content-Type: application/json


{
  "name": "test link 1",
  "realUrl": "https://google.com"
}

###


# Redirect (alias for realUrl)
GET {{baseRootUrl}}/vi
Accept: application/json


###
