scrape_configs:
  -
    job_name: server-mertics
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /metrics
    relabel_configs:
      - {target_label: server_label, replacement: backend}
    static_configs:
      - {targets: ['server:80']}